name: Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running test cases for predicting
      run: |
        cd app
        pytest test/test_predict.py
    - name: Running test cases for searching
      run: |
        cd app
        pytest test/test_search.py
    - name: Running test cases for util
      run: |
        cd app
        pytest test/test_util.py
    - name: Running test cases for chat
      run: |
        cd app
        pytest test/test_chat.py
    - name: Running test cases for new util
      run: |
        cd app
        pytest test/test_new.py
    
